### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nordtektiger** [nordtektiger/quickbuild#1]
# Quickbuild Development Roadmap
Quickbuild is currently under active development and changes will be made without prior notice. Feature requests are welcome!

## Tasks left until beta release:
- [x] File system searching
- [x] Config lexing
- [x] Config parsing
- [x] Interpreter
- - [x] Dependency resolution
- - [x] Expression evaluation
- [x] Bootstrapping Quickbuild

## Tasks left until stable release:
- [x] Incremental compilation: #10
- [ ] Additional fields & flags: #11
- [ ] Improved error messages: #9
- [ ] Finalize configuration syntax: #2
- [x] Performance improvements: #8
- [ ] Source code cleanup
- [ ] Reevaluate context scopes
- [ ] Strict dependency requirements
- [ ] --dry-run compatibility
- [ ] (Conditional compilation?)

**Comment by nordtektiger** [comment]
issue migrated to gitlab
